env: lab

proxmox:
  node: pve-node1
  template_id: 902
  storage: local-lvm
  bridge_lan: vmbr0
  bridge_internal: vmbr2
  bridge_mgmt: vmbr3
  ssh_key_path: /root/bernardo.pub
  ci_user: bernardo

vms:
  infra-core:
    vmid: 130
    hostname: infra-core
    cpu: 4
    memory_mb: 4096
    disk_gb: 60
    ip_mgmt: 172.16.0.10/24
    gw_mgmt: 172.16.0.1
    ip_internal: 10.10.0.10/24
    gw_internal: 10.10.0.1

  apps-core:
    vmid: 120
    hostname: apps-core
    cpu: 4
    memory_mb: 4096
    disk_gb: 80
    ip_internal: 10.10.0.20/24
    gw_internal: 10.10.0.1
