services:
  bookstack:
    image: lscr.io/linuxserver/bookstack:latest
    container_name: bookstack
    depends_on:
      - bookstack-db
    env_file:
      - ../../config/secrets/.env.apps-core
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Zurich
    volumes:
      - ./bookstack/config:/config
    networks:
      - proxy
      - internal
    restart: unless-stopped

  bookstack-db:
    image: lscr.io/linuxserver/mariadb:latest
    container_name: bookstack-db
    env_file:
      - ../../config/secrets/.env.apps-core
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Zurich
    volumes:
      - ./bookstack/db:/config
    networks:
      - internal
    restart: unless-stopped

  memos:
    image: neosmemo/memos:latest
    container_name: memos
    env_file:
      - ../../config/secrets/.env.apps-core
    volumes:
      - ./memos/data:/var/opt/memos
    networks:
      - proxy
      - internal
    restart: unless-stopped

networks:
  proxy:
    external: true
  internal:
    driver: bridge
