all:
  children:
    proxmox:
      hosts:
        proxmox.home.bernardolab.it:
          ansible_user: root
    homelab_core:
      hosts:
        homelab-core:
          ansible_host: 192.168.178.210
          ansible_user: debian
