services:
  immich-server:
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    container_name: immich-server
    user: "${IMMICH_UID_GID:-1001:100}"
    restart: unless-stopped
    ports:
      - "${IMMICH_PORT}:2283"
    env_file:
      - .env
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
    depends_on:
      redis:
        condition: service_healthy
      database:
        condition: service_healthy

  immich-machine-learning:
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    container_name: immich-machine-learning
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ${IMMICH_MODEL_CACHE_LOCATION}:/cache

  redis:
    image: ${IMMICH_REDIS_IMAGE:-redis:7.4-alpine}
    container_name: immich-redis
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ${IMMICH_REDIS_PATH}:/data

  database:
    image: tensorchord/pgvecto-rs:pg14-v0.3.0
    container_name: immich-database
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: --data-checksums
    volumes:
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d ${DB_DATABASE_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
